NourNursery.Portal/Areas/BasicInput/Controllers/FaqsController.cs
using Domain.Abstracts.BasicInput;
using NourNursery.Portal.Controllers;
using NourNursery.Portal.CustomAttributes;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models.ViewModel.BasicInput;
using Newtonsoft.Json;
using Portal.Resource.GlobalRes;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace NourNursery.Portal.Areas.BasicInput.Controllers
{
    [Area("BasicInput")]
    public class FaqsController : BaseController
    {
        #region Services
        private readonly IFaqsService _thisService;
        private IWebHostEnvironment _hostingEnvironment;
        #endregion

        #region Constructor
        public FaqsController(IFaqsService thisService, ICommonService commonService, IWebHostEnvironment hostingEnvironment, IHttpContextAccessor httpContextAccessor)
          : base(httpContextAccessor, commonService)
        {
            _thisService = thisService;
            _hostingEnvironment = hostingEnvironment;
            //   _commonService = new CommonService(lookupService);
        }
        #endregion


        #region Actions

        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Search()
        {
            var result =await _thisService.GetAllAsync();
            return PartialView(result);
        }

        public async Task<IActionResult> Create()
        {
            FaqsVm Obj = new FaqsVm();
            //ViewBag.ConditionerTypeId =await _commonService.FindAllConditionerTypes();
            //ViewBag.RoomTypeId = await _commonService.FindAllRoomTypes();

            return PartialView("~/Areas/BasicInput/Views/Faqs/Create.cshtml", Obj);
        }
        [HttpPost]
        public async Task<IActionResult> Create(FaqsVm viewModel)
        {
            viewModel.UserId = UserData.UserId;
            if (!string.IsNullOrWhiteSpace(viewModel.FaqsDetailsStr))
                viewModel.FaqsDetails = JsonConvert.DeserializeObject<List<FaqsDetailsVm>>(viewModel.FaqsDetailsStr);
            foreach (var item in viewModel.FaqsDetails)
            {
                item.CreateUserId = UserData.UserId;
            }



            var res = false;
            if (viewModel.Id == 0)
             res =await _thisService.AddAsync(viewModel);
            else
                res = await _thisService.UpdateAsync(viewModel);

            if (res)
            {
                return Json("success," + GlobalRes.MessageSuccuss.ToString());
            }
            else
                return Json("error," + GlobalRes.MessageError.ToString());

        }

        public FileResult DownloadAttachment(string FileName)
        {
            var path = System.IO.Path.Combine(_hostingEnvironment.WebRootPath, "Uploads", "FeaturesImages",
Path.GetFileName(FileName));
            if (System.IO.File.Exists(path))
            {
                byte[] fileBytes = System.IO.File.ReadAllBytes(path);
                return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, FileName);
            }
            return null;
        }
        public async Task<IActionResult> Edit(int id)
        {
            FaqsVm obj =await _thisService.GetByIdAsync(id);
          
            return PartialView("~/Areas/BasicInput/Views/Faqs/Create.cshtml", obj);
        }

      
        public async Task<IActionResult> Details(int id)
        {
            return PartialView(await _thisService.GetByIdAsync(id));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            FaqsVm obj = new FaqsVm();
            obj.Id = id;
            return PartialView("~/Areas/BasicInput/Views/Faqs/Delete.cshtml", obj);
        }


        [HttpPost]

        public async Task<JsonResult> DeleteRow(int Id)
        {
            if (await _thisService.DeleteAsync( Id) )
            {
                return Json("success," + GlobalRes.Messagedelete);
            }
            else
                return Json("error," + GlobalRes.MessageError);
        }


        #endregion
    }
}

NourNursery.Portal/Areas/BasicInput/Views/Faqs/Create.cshtml
@model Models.ViewModel.BasicInput.FaqsVm

    <script src="~/js/ckeditor/ckeditor.js"></script>
    <script src="~/js/ckeditor/build-config.js"></script>
    <script src="~/js/ckeditor/styles.js"></script>
    <script src="~/js/ckeditor/config.js"></script>

    <form asp-action="Create" asp-controller="Faqs" method="post" id="ModelForm">
        @Html.AntiForgeryToken()


        <div class=" bs-example-modal-lg modal-dialog modal-lg" tabindex="-1">
            <div class="modal-content">
                <div class="modal-header">
                    @*<button type="button" class="close" data-dismiss="modal">&times;</button>*@
                    <h4 class="modal-title">@GlobalRes.Faqs</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body">

                    <div class="row">
                        <div class="col-6">
                            <input asp-for="Id" hidden />

                            <label asp-for="TitleAr" class="control-label"></label>
                            <textarea asp-for="TitleAr" class="form-control"></textarea>




                        </div>
                        <div class="col-6">
                            <label asp-for="TitleEn" class="control-label"></label>
                            <textarea asp-for="TitleEn" class="form-control"></textarea>

                        </div>


                    </div>



                    <div class="row">
                        <div class="col-12 ">
                            <input asp-for="DetailId" hidden />

                            <label asp-for="QuestionAr" class="control-label"></label>
                            <textarea asp-for="QuestionAr" class="form-control"></textarea>

                        </div>


                        <div class="col-12 ">
                            <label asp-for="QuestionEn" class="control-label"></label>
                            <textarea asp-for="QuestionEn" class="form-control"></textarea>

                        </div>
                        <div class="col-12 ">
                            <label asp-for="DescAr" class="control-label"></label>
                            <textarea asp-for="DescAr" class="form-control"></textarea>

                        </div>
                        <div class="col-12 ">
                            <label asp-for="DescEn" class="control-label"></label>
                            <textarea asp-for="DescEn" class="form-control"></textarea>

                        </div>
                        <div class="modal-footer justify-content-end" style="text-align:left">
                            <button type="button" class="btn btn-outline-dark " onclick="AddFeature()">@GlobalRes.btnAdd</button>

                        </div>
                    </div>
                    <table id="FeatureTB" class="table table-bordered table-striped" style="width:100%">
                        <thead>
                            <tr>
                                <th>@BasicInputRes.QuestionAr</th>
                                <th>@BasicInputRes.QuestionEn</th>
                                <th>@BasicInputRes.DescAr</th>
                                <th>@BasicInputRes.DescEn</th>
                                <th>@GlobalRes.btnDelete</th>
                                <th>@GlobalRes.btnEdit</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.FaqsDetails != null)
                            {
                                @foreach (var item in Model.FaqsDetails)
                                {
                                    <tr>
                                        <td style="display:none">@item.Id</td>
                                        <td>@item.QuestionAr</td>
                                        <td>@item.QuestionEn</td>
                                        <td>@item.DescAr</td>
                                        <td>@item.DescEn</td>
                                        <td>
                                            <a class="" onclick="RemoveFeature(this);" style="color:red">
                                                <i class=" fa fa-trash"></i>
                                            </a>
                                        </td>
                                        <td>
                                            <a class="" onclick="EditFeature(this);">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                        </td>

                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer justify-content-end">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">@GlobalRes.btnCancel</button>
                    <button type="button" class="btn btn-primary " onclick="Save()">@GlobalRes.btnSave</button>

                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </form>

    <script type="text/javascript">
        CKEDITOR.replace('DescAr');
        CKEDITOR.replace('DescEn');
        CKEDITOR.replace('QuestionEn');
        CKEDITOR.replace('QuestionAr');
        CKEDITOR.replace('TitleAr');
        CKEDITOR.replace('TitleEn');
                //$(document).ready(function () {
                //    manageAbout.init();

                //})



    </script>

NourNursery.Portal/Areas/BasicInput/Views/Faqs/Delete.cshtml
@model Models.ViewModel.BasicInput.FaqsVm


<div class="modal-dialog" style="width: 900px;">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title"> @GlobalRes.btnDelete </h4>
        </div>
        <div class="modal-body" style="width :900px;">

            <h4 class="modal-title"> @GlobalRes.MessageDeleteDate ? </h4>
            <div class="row">
                <div class="col-md-3">
                    <input type="button" value="@GlobalRes.btnDelete" class="btn yellow Saveee" onclick="DeleteRow(@Model.Id)" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>
                </div>
            </div>
        </div>
    </div>
</div>

NourNursery.Portal/Areas/BasicInput/Views/Faqs/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = GlobalRes.Faqs;
}
<div class="row">
    <div class="col-lg-12 col-12">
        <!-- Basic Forms -->
        <div class="box">

            <div class="box-header with-border">
                <h4 class="box-title">
                    <i class="ti-agenda pl-1"></i>
                    @GlobalRes.Faqs
                </h4>

                <ul class="box-controls pull-right">
                    <li><a class="box-btn-close" href="#"></a></li>
                    <li><a class="box-btn-slide" href="#"></a></li>
                    <li><a class="box-btn-fullscreen" href="#"></a></li>
                </ul>
            </div>
            <!-- /.box-header -->
            <div class="box-body">


                <div class="box-body">
                    <div class="row">
                        <div class="col">
                            <form novalidate="">
                                

                                <div class="text-left">
                                    @*<button type="button" value="بحث" id="Search" class="btn btn-rounded bgbtn" onclick="search()">
                                        @GlobalRes.btnSearch
                                        <i class="ti-search"></i>
                                    </button>
                                    <button type="button" value="عرض الكل" id="ShowAll" class="btn btn-secondary purple" onclick="search()">
                                        @GlobalRes.btnShowAll
                                        <i class="fa fa-search-plus"></i>
                                    </button>*@
                                    <button type="button" class="btn btn-rounded btn-info" onclick="Create()"><i class="ti-plus"></i> @GlobalRes.btnAdd</button>

                                    @*<button type="submit" class="btn btn-rounded bgbtn">
                                            <i class="ti-search"></i>
                                            بحث
                                        </button>

                                        <button type="submit" class="btn btn-rounded btn-info">
                                            <i class="ti-plus"></i>
                                            اضف
                                        </button>*@

                                    @*<button type="submit" class="btn btn-rounded btn-danger"><i class="ti-trash"></i> حذف</button>*@
                                </div>
                            </form>

                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>

                <!-- /.row -->
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <div class="col-12">

        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">

                    <i class="ti-files pl-1"></i>
                    @GlobalRes.SearchResult
                </h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div  id="SearchTableContainer" class="table-responsive">

               
                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>

    



</div>





<div class="modal fade" id="myModalAddEdit" role="dialog"  ></div>

@section Scripts {

    <script src="~/PageScript/BasicInput/manageFaqs.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            manageFaqs.init();

        })

    </script>


}

NourNursery.Portal/Areas/BasicInput/Views/Faqs/Search.cshtml
@model IEnumerable<Models.ViewModel.BasicInput.FaqsVm>
@{
    int str = 1;
}
<div class="panel">
    <table id="example5" class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>@BasicInputRes.TitleAr</th>
                <th>@BasicInputRes.TitleEn</th>
                <th>@GlobalRes.Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.TitleAr</td>
                    <td>@item.TitleEn</td>
                    <td>
                        <div class="btn-group display-inline pull-right text-align-left hidden-tablet">
                            <button class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-cog fa-lg"></i>
                            </button>
                            <ul class="dropdown-menu dropdown-menu-xs pull-right">
                                <li>
                                    <input type="button" id="btnUpdate" onclick="Edit(@item.Id)" value="@GlobalRes.btnEdit" />
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <input type="button" id="btnDelete" onclick="Delete(@item.Id)" value="@GlobalRes.btnDelete" />
                                </li>
                                <li class="divider"></li>
                                <li class="text-align-center">
                                    <a href="javascript:void(0);">@GlobalRes.btnCancel</a>
                                </li>
                            </ul>
                        </div>
                    </td>

                </tr>
            }
        </tbody>
    </table>
    <br />
    <br />
    <br />
</div>
<script type="text/javascript">
    $(function () {
        $('#example5').DataTable({

        });
    });

</script>