NourNursery.Portal/Areas/BasicInput/Controllers/SliderImage1Controller.cs
using Domain.Abstracts.BasicInput;
using NourNursery.Portal.Controllers;
using NourNursery.Portal.CustomAttributes;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Models.ViewModel.BasicInput;
using Portal.Resource.GlobalRes;
using System;
using System.IO;
using System.Threading.Tasks;

namespace NourNursery.Portal.Areas.BasicInput.Controllers
{
    [Area("BasicInput")]
    public class SliderImage1Controller : BaseController
    {
        #region Services
        private readonly ISlidersService _thisService;
        private IWebHostEnvironment _hostingEnvironment;
        #endregion

        #region Constructor
        public SliderImage1Controller(ISlidersService thisService, ICommonService commonService, IWebHostEnvironment hostingEnvironment, IHttpContextAccessor httpContextAccessor)
          : base(httpContextAccessor, commonService)
        {
            _thisService = thisService;
            _hostingEnvironment = hostingEnvironment;
            //   _commonService = new CommonService(lookupService);
        }
        #endregion


        #region Actions

        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Search()
        {
            var result = await _thisService.GetAllByTypeAsync(1);
            return PartialView(result);
        }

        public async Task<IActionResult> Create()
        {
           SlidersVm Obj = new SlidersVm();
            //ViewBag.ConditionerTypeId =await _commonService.FindAllConditionerTypes();
            //ViewBag.RoomTypeId = await _commonService.FindAllRoomTypes();

            return PartialView("~/Areas/BasicInput/Views/SliderImage1/Create.cshtml", Obj);
        }
        [HttpPost]
        public async Task<IActionResult> Create(SlidersVm viewModel, IFormFile Image)
        {
            viewModel.UserId = UserData.UserId;
            if (Image != null)
            {
                var FileName = Image.FileName;
                var path = System.IO.Path.Combine(_hostingEnvironment.WebRootPath, "Uploads", "Media");

                string imgPath = Path.Combine(path, FileName);
                if (System.IO.File.Exists(imgPath))
                {
                    FileName = DateTime.Now.ToString("ddMMyyyhhMMssfff") + FileName;
                }
                if (Image.Length > 0)
                {
                    using (var fileStream = new FileStream(Path.Combine(path, FileName), FileMode.Create))
                    {
                        await Image.CopyToAsync(fileStream);
                    }
                    viewModel.Image = "Uploads/Media/" + FileName;
                }
            }

            var res = false;
            if (viewModel.Id == 0)
                res = await _thisService.AddAsync(viewModel);
            else
                res = await _thisService.UpdateAsync(viewModel);

            if (res)
            {
                return Json("success," + GlobalRes.MessageSuccuss.ToString());
            }
            else
                return Json("error," + GlobalRes.MessageError.ToString());

        }

        public FileResult DownloadAttachment(string FileName)
        {
            var path = System.IO.Path.Combine(_hostingEnvironment.WebRootPath, "Uploads", "Media",
                        Path.GetFileName(FileName));
            if (System.IO.File.Exists(path))
            {
                byte[] fileBytes = System.IO.File.ReadAllBytes(path);
                return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, FileName);
            }
            return null;
        }
        public async Task<IActionResult> Edit(int id)
        {
            SlidersVm obj = await _thisService.GetByIdAsync(id);

            return PartialView("~/Areas/BasicInput/Views/SliderImage1/Create.cshtml", obj);
        }


        public async Task<IActionResult> Details(int id)
        {
            return PartialView(await _thisService.GetByIdAsync(id));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            SlidersVm obj = new SlidersVm();
            obj.Id = id;
            return PartialView("~/Areas/BasicInput/Views/SliderImage1/Delete.cshtml", obj);
        }


        [HttpPost]

        public async Task<JsonResult> DeleteRow(int Id)
        {
            if (await _thisService.DeleteAsync(Id))
            {
                return Json("success," + GlobalRes.Messagedelete);
            }
            else
                return Json("error," + GlobalRes.MessageError);
        }


        #endregion
    }
}

NourNursery.Portal/Areas/BasicInput/Views/SliderImage1/Create.cshtml
@model Models.ViewModel.BasicInput.SlidersVm
<script src="~/js/ckeditor/ckeditor.js"></script>
<script src="~/js/ckeditor/build-config.js"></script>
<script src="~/js/ckeditor/styles.js"></script>
<script src="~/js/ckeditor/config.js"></script>
<form asp-action="Create" asp-controller="SliderImage1" method="post" id="ModelForm">
    @Html.AntiForgeryToken()


    <div class=" bs-example-modal-lg modal-dialog modal-lg" tabindex="-1">
        <div class="modal-content">
            <div class="modal-header">
                @*<button type="button" class="close" data-dismiss="modal">&times;</button>*@
                <h4 class="modal-title">@GlobalRes.SliderImage1</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">

                <div class="row">
                    <div class="col-6">
                        <input asp-for="Id" hidden />
                        <input asp-for="Type" value="1" hidden />
                        <input asp-for="Image" hidden />

                        <label asp-for="DescAr" class="control-label"></label>
                        <textarea asp-for="DescAr" class="form-control"></textarea>
                    </div>
                    <div class="col-6">
                        <label asp-for="DescEn" class="control-label"></label>
                        <textarea asp-for="DescEn" class="form-control"></textarea>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6 ">
                        <label asp-for="Image" class="control-label"></label>

                        <input type="file" name="Image" id="Image" />
                        <br />

                        @if (!string.IsNullOrEmpty(Model.Image))
                        {
                            <img style="width: 200px;height: 100px;" src="~/@(Model.Image)">
                            <a target="_blank" class="fa fa-download" href="~/@(Model.Image)"></a>
                        }
                    </div>


                </div>

            </div>
            <div class="modal-footer justify-content-end">
                <button type="button" class="btn btn-danger" data-dismiss="modal">@GlobalRes.btnCancel</button>
                <button type="button" class="btn btn-primary " onclick="Save()">@GlobalRes.btnSave</button>

            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</form>
<script type="text/javascript">
    CKEDITOR.replace('DescAr');
    CKEDITOR.replace('DescEn');
</script>

NourNursery.Portal/Areas/BasicInput/Views/SliderImage1/Delete.cshtml
@model Models.ViewModel.BasicInput.SlidersVm


<div class="modal-dialog" style="width: 900px;">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title"> @GlobalRes.btnDelete </h4>
        </div>
        <div class="modal-body" style="width :900px;">

            <h4 class="modal-title"> @GlobalRes.MessageDeleteDate ? </h4>
            <div class="row">
                <div class="col-md-3">
                    <input type="button" value="@GlobalRes.btnDelete" class="btn yellow Saveee" onclick="DeleteRow(@Model.Id)" />
                    <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.btnCancel</button>
                </div>
            </div>
        </div>
    </div>
</div>

NourNursery.Portal/Areas/BasicInput/Views/SliderImage1/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = GlobalRes.SliderImage1;
}
<div class="row">
    <div class="col-lg-12 col-12">
        <!-- Basic Forms -->
        <div class="box">

            <div class="box-header with-border">
                <h4 class="box-title">
                    <i class="ti-agenda pl-1"></i>
                    @GlobalRes.SliderImage1
                </h4>

                <ul class="box-controls pull-right">
                    <li><a class="box-btn-close" href="#"></a></li>
                    <li><a class="box-btn-slide" href="#"></a></li>
                    <li><a class="box-btn-fullscreen" href="#"></a></li>
                </ul>
            </div>
            <!-- /.box-header -->
            <div class="box-body">


                <div class="box-body">
                    <div class="row">
                        <div class="col">
                            <form novalidate="">


                                <div class="text-left">
                                    @*<button type="button" value="بحث" id="Search" class="btn btn-rounded bgbtn" onclick="search()">
                                            @GlobalRes.btnSearch
                                            <i class="ti-search"></i>
                                        </button>
                                        <button type="button" value="عرض الكل" id="ShowAll" class="btn btn-secondary purple" onclick="search()">
                                            @GlobalRes.btnShowAll
                                            <i class="fa fa-search-plus"></i>
                                        </button>*@
                                    <button type="button" class="btn btn-rounded btn-info" onclick="Create()"><i class="ti-plus"></i> @GlobalRes.btnAdd</button>

                                    @*<button type="submit" class="btn btn-rounded bgbtn">
                                            <i class="ti-search"></i>
                                            بحث
                                        </button>

                                        <button type="submit" class="btn btn-rounded btn-info">
                                            <i class="ti-plus"></i>
                                            اضف
                                        </button>*@

                                    @*<button type="submit" class="btn btn-rounded btn-danger"><i class="ti-trash"></i> حذف</button>*@
                                </div>
                            </form>

                        </div>
                        <!-- /.col -->
                    </div>
                    <!-- /.row -->
                </div>

                <!-- /.row -->
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <div class="col-12">

        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">

                    <i class="ti-files pl-1"></i>
                    @GlobalRes.SearchResult
                </h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div id="SearchTableContainer" class="table-responsive">


                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>





</div>





<div class="modal fade" id="myModalAddEdit" role="dialog"></div>

@section Scripts {

    <script src="~/PageScript/BasicInput/manageSliderImage1.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            manageSliderImage1.init();

        })

    </script>


}

NourNursery.Portal/Areas/BasicInput/Views/SliderImage1/Search.cshtml
@model IEnumerable<Models.ViewModel.BasicInput.SlidersVm>
@using Library.Helpers.Utilities;
@{
    int str = 1;
}
<div class="panel">
    <table id="example5" class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>@BasicInputRes.DescAr</th>
                <th>@BasicInputRes.DescEn</th>
                <th>@BasicInputRes.Image</th>
                @*<th>@BasicInputRes.DescAr</th>
                    <th>@BasicInputRes.DescEn</th>*@
                <th>@GlobalRes.Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td> @Html.Raw(item.DescAr)</td>
                    <td>@Html.Raw(item.DescEn)</td>
                    <td>
                        <img style="width: 100px;height: 50px;" src="~/@(item.Image)">
                        <a target="_blank" class="fa fa-download" href="~/@(item.Image)"></a>
                    </td>
                    @*<td>@item.DescAr</td>
                        <td>@item.DescEn</td>*@
                    <td>
                        <div class="btn-group display-inline pull-right text-align-left hidden-tablet">
                            <button class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-cog fa-lg"></i>
                            </button>
                            <ul class="dropdown-menu dropdown-menu-xs pull-right">
                                <li>
                                    <input type="button" id="btnUpdate" onclick="Edit(@item.Id)" value="@GlobalRes.btnEdit" />
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <input type="button" id="btnDelete" onclick="Delete(@item.Id)" value="@GlobalRes.btnDelete" />
                                </li>
                                <li class="divider"></li>
                                <li class="text-align-center">
                                    <a href="javascript:void(0);">@GlobalRes.btnCancel</a>
                                </li>
                            </ul>
                        </div>
                    </td>

                </tr>
            }
        </tbody>
    </table>
    <br />
    <br />
    <br />
</div>
<script type="text/javascript">
    $(function () {
        $('#example5').DataTable({

        });
    });

</script>